;;;; 增强型 原生修改器：配置 INI 文件（开始） ;;;;

;;; （删除此文件以恢复默认颜色配置） ;;;

;; 菜单颜色（开始） ;;
;; 请遵循 RGBA 颜色系统，每个颜色组件的值范围为 0 ~ 255 ;;
[菜单颜色]
; 标题文本 ;
colHeaderTextr=255
colHeaderTextg=180
colHeaderTextb=0
colHeaderTexta=255
; 标题框 ;
colHeaderRectr=0
colHeaderRectg=0
colHeaderRectb=0
colHeaderRecta=200
; 项目文本 ;
colItemTextr=0
colItemTextg=255
colItemTextb=255
colItemTexta=255
; 项目框 ;
colItemRectr=255
colItemRectg=255
colItemRectb=255
colItemRecta=80
; 活动项目文本 ;
colItemActiveTextr=0
colItemActiveTextg=0
colItemActiveTextb=0
colItemActiveTexta=255
; 活动项目框 ;
colItemActiveRectr=255
colItemActiveRectg=180
colItemActiveRectb=0
colItemActiveRecta=200
; 锁定的列表项 ;
colListItemLockedr=255
colListItemLockedg=255
colListItemLockedb=255
colListItemLockeda=255
; 解锁的列表项 ;
colListItemUnlockedr=125
colListItemUnlockedg=125
colListItemUnlockedb=125
colListItemUnlockeda=255
; 实心的通缉星 ;
colWantedr=255
colWantedg=255
colWantedb=255
colWanteda=255
; 空心的通缉星 ;
colUnwantedr=100
colUnwantedg=100
colUnwantedb=100
colUnwanteda=255
; 子菜单存在时的符号 ;
colChildExistsr=225
colChildExistsg=225
colChildExistsb=225
colChildExistsa=255
; 车辆预览图像边框 ;
colSpriteBorderr=0
colSpriteBorderg=0
colSpriteBorderb=0
colSpriteBordera=180
;; 菜单颜色（结束） ;;

;;;; 增强型 原生修改器：配置 INI 文件（结束） ;;;;
